name: research
channels:
  - defaults
  - conda-forge
dependencies:
  - compas
  - xgboost
  - bayesian-optimization
  - tqdm
  - shap
  - pip
  - pip:
    - numpy
    - pandas
    - scikit-learn
    - plotly
